/**
 * This data is generated by nvdb/apiskriv on dryruns
 */

module.exports = {
  /* VALIDATOR
  ----------------------------------------------------------------------------*/
  validator: {
    // ---
    less: {
      mottatt: '2015-07-27T14:09:24.077',
      fremdrift: 'UTFØRT',
      resultat: {
        feil: [],
        advarsel: [],
        vegObjekter: [
          {
            feil: [],
            advarsel: [
              {
                melding: 'Verdien 1800 for egenskapstype 10288 (Byggeår) er mindre enn anbefalt minmumsverdi: 1900',
                kode: 'MINDRE_ENN_ANBEFALT_MINIMUM',
                referanse: 'http://labs.vegdata.no/nvdb-datakatalog/103',
                egenskapTypeId: 10288
              }
            ],
            tempId: '-1'
          }
        ]
      },
      eier: 'extscs'
    },

    // ---
    more: {
      mottatt: '2015-07-27T14:14:38.444',
      fremdrift: 'UTFØRT',
      resultat: {
        feil: [],
        advarsel: [],
        vegObjekter: [
          {
            feil: [],
            advarsel: [
              {
                melding: 'Verdien 2500 for egenskapstype 10288 (Byggeår) er større enn anbefalt maksimumsverdi: 2100',
                kode: 'STØRRE_ENN_ANBEFALT_MAKSIMUM',
                referanse: 'http://labs.vegdata.no/nvdb-datakatalog/103',
                egenskapTypeId: 10288
              }
            ],
            tempId: '-1'
          }
        ]
      },
      eier: 'extscs'
    },

    // ---
    missing: {
      mottatt: '2015-07-27T14:11:11.449',
      fremdrift: 'UTFØRT',
      resultat: {
        feil: [],
        advarsel: [],
        vegObjekter: [
          {
            feil: [],
            advarsel: [
              {
                melding: 'Objektet, av typen 103 (Fartsdemper), mangler anbefalte egenskaper: [Byggeår (10288)]',
                kode: 'MANGLER_ANBEFALTE_EGENSKAPER',
                referanse: 'http://labs.vegdata.no/nvdb-datakatalog/103'
              }
            ],
            tempId: '-1'
          }
        ]
      },
      eier: 'extscs'
    },

    // ---
    success: {
      mottatt: '2015-07-27T12:28:39.939',
      fremdrift: 'UTFØRT',
      resultat:{
        feil: [],
        advarsel: [],
        vegObjekter: [
          {
            tempId: '-1'
          }
        ]
      },
      eier: 'extscs'
    }
  },

  /* ENDRINGSSETT
  ----------------------------------------------------------------------------*/
  endringssett: {
    success: [
      {
        rel: 'self',
        src: 'https://www.utv.vegvesen.no/nvdb/apiskriv/v2/endringssett/f87e1731-bf93-4f35-9af6-7b6d120624c2'
      },
      {
        rel: 'start',
        src: 'https://www.utv.vegvesen.no/nvdb/apiskriv/v2/endringssett/f87e1731-bf93-4f35-9af6-7b6d120624c2/start'
      },
      {
        rel: 'kanseller',
        src: 'https://www.utv.vegvesen.no/nvdb/apiskriv/v2/endringssett/f87e1731-bf93-4f35-9af6-7b6d120624c2/kanseller'
      },
      {
        rel: 'status',
        src: 'https://www.utv.vegvesen.no/nvdb/apiskriv/v2/endringssett/f87e1731-bf93-4f35-9af6-7b6d120624c2/status'
      },
      {
        rel: 'fremdrift',
        src: 'https://www.utv.vegvesen.no/nvdb/apiskriv/v2/endringssett/f87e1731-bf93-4f35-9af6-7b6d120624c2/fremdrift'
      }
    ]
  },

  /* START
  ----------------------------------------------------------------------------*/
  start: {
    success: [
      {
        rel: 'fremdrift',
        src: 'https://www.utv.vegvesen.no/nvdb/apiskriv/v2/endringssett/f87e1731-bf93-4f35-9af6-7b6d120624c2/fremdrift'
      },
      {
        rel: 'status',
        src: 'https://www.utv.vegvesen.no/nvdb/apiskriv/v2/endringssett/f87e1731-bf93-4f35-9af6-7b6d120624c2/status'
      },
      {
        rel: 'self',
        src: 'https://www.utv.vegvesen.no/nvdb/apiskriv/v2/endringssett/f87e1731-bf93-4f35-9af6-7b6d120624c2'
      }
    ]
  },

  /* FREMDRIFT
  ----------------------------------------------------------------------------*/
  fremdrift: {
    working: 'BEHANDLER',
    success: 'UTFØRT',
    err: 'AVVIST'
  },

  status: {
    status: {
      "mottatt": "2015-07-29T14:55:02.276",
      "fremdrift": "AVVIST",
      "avvistårsak": "VALIDERINGSFEIL",
      "resultat": {
        "feil":[],
        "advarsel":[],
        "vegObjekter":[
          {
            "feil":[
              {
                "melding": "Versjon oppgitt for oppdatering er ikke aktiv versjon. Aktiv versjon er 2",
                "kode": "VERSJONSKONFLIKT"
              }
            ],
            "advarsel":[
              {
                "melding": "Objektet, av typen 103 (Fartsdemper), mangler anbefalte egenskaper: [Byggeår (10288)]",
                "kode": "MANGLER_ANBEFALTE_EGENSKAPER",
                "referanse": "http://labs.vegdata.no/nvdb-datakatalog/103"
              }
            ],
            "nvdbId":489331933
          }
        ]
      },
      "eier": "extscs"
    }
  }
}
